name: diamante_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  share_plus: ^7.2.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
